### ISSUE TITLE
add full page link to codepen demo

### ISSUE THREAD

**Issue by hchiam** [hchiam/language-user-interface#39]
https://cdn.jsdelivr.net/gh/hchiam/codepen-full-page-link@2.0.0/codepen-full-page-link.js

```css
body > p:first-child {
  background: red;
  width: 100%;
  display: flex;
  justify-content: center;
  gap: 0.25rem;
  color: white;
}
```
